// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package devops_integral_upm_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserByIdReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdReq) Reset()         { *m = GetUserByIdReq{} }
func (m *GetUserByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdReq) ProtoMessage()    {}
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdReq.Unmarshal(m, b)
}
func (m *GetUserByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdReq.Marshal(b, m, deterministic)
}
func (m *GetUserByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdReq.Merge(m, src)
}
func (m *GetUserByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdReq.Size(m)
}
func (m *GetUserByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdReq proto.InternalMessageInfo

func (m *GetUserByIdReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CheckUserReq struct {
	TenantId             int32    `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserReq) Reset()         { *m = CheckUserReq{} }
func (m *CheckUserReq) String() string { return proto.CompactTextString(m) }
func (*CheckUserReq) ProtoMessage()    {}
func (*CheckUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CheckUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserReq.Unmarshal(m, b)
}
func (m *CheckUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserReq.Marshal(b, m, deterministic)
}
func (m *CheckUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserReq.Merge(m, src)
}
func (m *CheckUserReq) XXX_Size() int {
	return xxx_messageInfo_CheckUserReq.Size(m)
}
func (m *CheckUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserReq proto.InternalMessageInfo

func (m *CheckUserReq) GetTenantId() int32 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *CheckUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CheckUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TenantId             int32    `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ChName               string   `protobuf:"bytes,4,opt,name=chName,proto3" json:"chName,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Admin                bool     `protobuf:"varint,8,opt,name=admin,proto3" json:"admin,omitempty"`
	CreatedOn            int32    `protobuf:"varint,9,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,10,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int32    `protobuf:"varint,11,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,12,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int32    `protobuf:"varint,13,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetTenantId() int32 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetChName() string {
	if m != nil {
		return m.ChName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *User) GetCreatedOn() int32 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *User) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *User) GetUpdatedOn() int32 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *User) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *User) GetDeletedOn() int32 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

type CreateUserReq struct {
	TenantId             int32    `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ChName               string   `protobuf:"bytes,3,opt,name=chName,proto3" json:"chName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedBy            string   `protobuf:"bytes,7,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,8,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetTenantId() int32 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *CreateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserReq) GetChName() string {
	if m != nil {
		return m.ChName
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *CreateUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type UpdateUserReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TenantId             int32    `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ChName               string   `protobuf:"bytes,4,opt,name=chName,proto3" json:"chName,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,7,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserReq) GetTenantId() int32 {
	if m != nil {
		return m.TenantId
	}
	return 0
}

func (m *UpdateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserReq) GetChName() string {
	if m != nil {
		return m.ChName
	}
	return ""
}

func (m *UpdateUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type GetUserResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUserResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CheckUserResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserResp) Reset()         { *m = CheckUserResp{} }
func (m *CheckUserResp) String() string { return proto.CompactTextString(m) }
func (*CheckUserResp) ProtoMessage()    {}
func (*CheckUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CheckUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserResp.Unmarshal(m, b)
}
func (m *CheckUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserResp.Marshal(b, m, deterministic)
}
func (m *CheckUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserResp.Merge(m, src)
}
func (m *CheckUserResp) XXX_Size() int {
	return xxx_messageInfo_CheckUserResp.Size(m)
}
func (m *CheckUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserResp proto.InternalMessageInfo

func (m *CheckUserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckUserResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserByIdReq)(nil), "devops.integral.upm.srv.service.GetUserByIdReq")
	proto.RegisterType((*CheckUserReq)(nil), "devops.integral.upm.srv.service.CheckUserReq")
	proto.RegisterType((*User)(nil), "devops.integral.upm.srv.service.User")
	proto.RegisterType((*CreateUserReq)(nil), "devops.integral.upm.srv.service.CreateUserReq")
	proto.RegisterType((*UpdateUserReq)(nil), "devops.integral.upm.srv.service.UpdateUserReq")
	proto.RegisterType((*GetUserResp)(nil), "devops.integral.upm.srv.service.GetUserResp")
	proto.RegisterType((*CheckUserResp)(nil), "devops.integral.upm.srv.service.CheckUserResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0xfd, 0x49, 0xdb, 0xd3, 0xad, 0x17, 0x83, 0x2c, 0x43, 0x11, 0x2c, 0x01, 0xa1, 0x17,
	0x1a, 0x61, 0xbd, 0xf2, 0xb6, 0xbd, 0x90, 0xbd, 0x51, 0x88, 0xec, 0x03, 0xcc, 0x66, 0x0e, 0xdb,
	0x6a, 0xf3, 0xe3, 0x4c, 0x5a, 0x29, 0xf8, 0x6e, 0xe2, 0xab, 0xe8, 0x8b, 0xc8, 0x99, 0x69, 0x26,
	0x49, 0xb1, 0xb6, 0x51, 0xd8, 0xcb, 0xef, 0x7c, 0xf3, 0x9d, 0x9f, 0x2f, 0x73, 0x26, 0x00, 0x5b,
	0x8d, 0x2a, 0xcc, 0x55, 0x56, 0x64, 0xec, 0xb9, 0xc4, 0x5d, 0x96, 0xeb, 0x70, 0x9d, 0x16, 0xf8,
	0xa0, 0xc4, 0x26, 0xdc, 0xe6, 0x49, 0xa8, 0xd5, 0x2e, 0xd4, 0xa8, 0x76, 0xeb, 0x18, 0x83, 0x39,
	0x3c, 0x79, 0x87, 0xc5, 0x9d, 0x46, 0xb5, 0xd8, 0xdf, 0xca, 0x08, 0xbf, 0xb0, 0x6b, 0xf0, 0x29,
	0xc1, 0xad, 0xe4, 0xde, 0xcc, 0x9b, 0xf7, 0xa3, 0x03, 0x0a, 0xee, 0xe1, 0x6a, 0xb9, 0xc2, 0xf8,
	0x33, 0x9d, 0xa5, 0x73, 0x53, 0x18, 0x16, 0x98, 0x8a, 0xb4, 0x70, 0x27, 0x1d, 0x26, 0x8e, 0x54,
	0xa9, 0x48, 0x90, 0x77, 0x66, 0xde, 0x7c, 0x14, 0x39, 0x4c, 0x5c, 0x2e, 0xb4, 0xfe, 0x9a, 0x29,
	0xc9, 0xbb, 0x96, 0x2b, 0x71, 0xf0, 0xb3, 0x03, 0x3d, 0xca, 0x7f, 0xaa, 0x89, 0x46, 0xd1, 0xce,
	0x5f, 0x8a, 0x76, 0x8f, 0x8a, 0x5e, 0x83, 0x1f, 0xaf, 0xde, 0x13, 0xd3, 0x33, 0xcc, 0x01, 0x35,
	0x9a, 0xe9, 0x37, 0x9b, 0x61, 0x4f, 0xa1, 0x8f, 0x89, 0x58, 0x6f, 0xb8, 0x6f, 0x08, 0x0b, 0x28,
	0x9a, 0xaf, 0xb2, 0x14, 0xf9, 0xc0, 0x46, 0x0d, 0xa0, 0xa8, 0x90, 0xc9, 0x3a, 0xe5, 0xc3, 0x99,
	0x37, 0x1f, 0x46, 0x16, 0xb0, 0x67, 0x30, 0x8a, 0x15, 0x8a, 0x02, 0xe5, 0x87, 0x94, 0x8f, 0x4c,
	0xbb, 0x55, 0xa0, 0xc6, 0x2e, 0xf6, 0x1c, 0x4c, 0xb6, 0x2a, 0x40, 0xec, 0x36, 0x97, 0x07, 0xed,
	0xd8, 0x6a, 0x5d, 0xa0, 0xc6, 0x2e, 0xf6, 0xfc, 0xca, 0x6a, 0x5d, 0x80, 0x58, 0x89, 0x1b, 0xb4,
	0xda, 0x89, 0xd5, 0xba, 0x40, 0xf0, 0xcb, 0x83, 0xc9, 0xd2, 0xd4, 0xf9, 0xdf, 0x4f, 0x59, 0xb9,
	0xda, 0x3d, 0xe9, 0x6a, 0xef, 0x94, 0xab, 0xfd, 0x3f, 0xba, 0xea, 0xd7, 0x5d, 0x6d, 0x38, 0x34,
	0x38, 0xed, 0xd0, 0x62, 0x6f, 0x7c, 0xaf, 0x7b, 0x10, 0xfc, 0xf0, 0x60, 0x72, 0x67, 0x50, 0x39,
	0xe5, 0x63, 0xdd, 0xa9, 0x96, 0x13, 0x56, 0x33, 0x0c, 0x8e, 0x67, 0xf8, 0x06, 0xe3, 0xc3, 0x72,
	0x46, 0xa8, 0x73, 0xc6, 0x61, 0xa0, 0xb7, 0x71, 0x8c, 0x5a, 0x9b, 0x09, 0x86, 0x51, 0x09, 0x89,
	0x49, 0x50, 0x6b, 0xf1, 0x50, 0x7e, 0xa3, 0x12, 0xb2, 0xb7, 0xd0, 0xa3, 0x86, 0x4d, 0xf3, 0xe3,
	0x9b, 0x17, 0xe1, 0x99, 0xf7, 0x20, 0x34, 0xc5, 0x8c, 0x24, 0x58, 0xc2, 0xa4, 0xb6, 0xf0, 0xff,
	0x56, 0xff, 0xe6, 0x7b, 0x17, 0xc6, 0x94, 0xe0, 0xa3, 0xcd, 0xcf, 0x36, 0x6e, 0x24, 0x7a, 0x6f,
	0xd8, 0xeb, 0xb3, 0x0d, 0x35, 0x5f, 0xa7, 0xe9, 0xcb, 0x4b, 0x05, 0xa6, 0xe3, 0x4f, 0x30, 0x72,
	0x23, 0xb0, 0x57, 0x67, 0xa5, 0xf5, 0xf7, 0x6d, 0x1a, 0xb6, 0x39, 0x6e, 0x6a, 0x41, 0xb5, 0x55,
	0xec, 0x02, 0x75, 0x7d, 0x05, 0x5b, 0xcf, 0x05, 0xd5, 0xdd, 0xbe, 0xa0, 0x56, 0x63, 0x11, 0xda,
	0xd5, 0xba, 0xf7, 0xcd, 0x9f, 0xe4, 0xcd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x1c, 0xbe,
	0x9d, 0x57, 0x06, 0x00, 0x00,
}
