// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package devops_integral_upm_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	// 根据用户ID获取用户
	GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...client.CallOption) (*GetUserResp, error)
	// 根据用户名密码校验密码是否正确
	CheckUser(ctx context.Context, in *CheckUserReq, opts ...client.CallOption) (*GetUserResp, error)
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...client.CallOption) (*GetUserResp, error)
	// 更新用户
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*GetUserResp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "devops.integral.upm.srv.service"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserById", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CheckUser(ctx context.Context, in *CheckUserReq, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "UserService.CheckUser", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateUser", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...client.CallOption) (*GetUserResp, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUser", in)
	out := new(GetUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 根据用户ID获取用户
	GetUserById(context.Context, *GetUserByIdReq, *GetUserResp) error
	// 根据用户名密码校验密码是否正确
	CheckUser(context.Context, *CheckUserReq, *GetUserResp) error
	// 创建用户
	CreateUser(context.Context, *CreateUserReq, *GetUserResp) error
	// 更新用户
	UpdateUser(context.Context, *UpdateUserReq, *GetUserResp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetUserById(ctx context.Context, in *GetUserByIdReq, out *GetUserResp) error
		CheckUser(ctx context.Context, in *CheckUserReq, out *GetUserResp) error
		CreateUser(ctx context.Context, in *CreateUserReq, out *GetUserResp) error
		UpdateUser(ctx context.Context, in *UpdateUserReq, out *GetUserResp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetUserById(ctx context.Context, in *GetUserByIdReq, out *GetUserResp) error {
	return h.UserServiceHandler.GetUserById(ctx, in, out)
}

func (h *userServiceHandler) CheckUser(ctx context.Context, in *CheckUserReq, out *GetUserResp) error {
	return h.UserServiceHandler.CheckUser(ctx, in, out)
}

func (h *userServiceHandler) CreateUser(ctx context.Context, in *CreateUserReq, out *GetUserResp) error {
	return h.UserServiceHandler.CreateUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUser(ctx context.Context, in *UpdateUserReq, out *GetUserResp) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}
