// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package devops_integral_upm_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoleReq struct {
	RoleName             string   `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`
	RoleDesc             string   `protobuf:"bytes,2,opt,name=roleDesc,proto3" json:"roleDesc,omitempty"`
	CreatedBy            string   `protobuf:"bytes,3,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleReq) Reset()         { *m = CreateRoleReq{} }
func (m *CreateRoleReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoleReq) ProtoMessage()    {}
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func (m *CreateRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleReq.Unmarshal(m, b)
}
func (m *CreateRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleReq.Marshal(b, m, deterministic)
}
func (m *CreateRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleReq.Merge(m, src)
}
func (m *CreateRoleReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoleReq.Size(m)
}
func (m *CreateRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleReq proto.InternalMessageInfo

func (m *CreateRoleReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateRoleReq) GetRoleDesc() string {
	if m != nil {
		return m.RoleDesc
	}
	return ""
}

func (m *CreateRoleReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

type UpdateRoleReq struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	RoleDesc             string   `protobuf:"bytes,3,opt,name=roleDesc,proto3" json:"roleDesc,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,4,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleReq) Reset()         { *m = UpdateRoleReq{} }
func (m *UpdateRoleReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleReq) ProtoMessage()    {}
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{1}
}

func (m *UpdateRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleReq.Unmarshal(m, b)
}
func (m *UpdateRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleReq.Marshal(b, m, deterministic)
}
func (m *UpdateRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleReq.Merge(m, src)
}
func (m *UpdateRoleReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleReq.Size(m)
}
func (m *UpdateRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleReq proto.InternalMessageInfo

func (m *UpdateRoleReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UpdateRoleReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UpdateRoleReq) GetRoleDesc() string {
	if m != nil {
		return m.RoleDesc
	}
	return ""
}

func (m *UpdateRoleReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type DeleteRoleReq struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,2,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleReq) Reset()         { *m = DeleteRoleReq{} }
func (m *DeleteRoleReq) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleReq) ProtoMessage()    {}
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{2}
}

func (m *DeleteRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleReq.Unmarshal(m, b)
}
func (m *DeleteRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleReq.Marshal(b, m, deterministic)
}
func (m *DeleteRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleReq.Merge(m, src)
}
func (m *DeleteRoleReq) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleReq.Size(m)
}
func (m *DeleteRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleReq proto.InternalMessageInfo

func (m *DeleteRoleReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *DeleteRoleReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type DeleteRoleResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoleResp) Reset()         { *m = DeleteRoleResp{} }
func (m *DeleteRoleResp) String() string { return proto.CompactTextString(m) }
func (*DeleteRoleResp) ProtoMessage()    {}
func (*DeleteRoleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{3}
}

func (m *DeleteRoleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoleResp.Unmarshal(m, b)
}
func (m *DeleteRoleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoleResp.Marshal(b, m, deterministic)
}
func (m *DeleteRoleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoleResp.Merge(m, src)
}
func (m *DeleteRoleResp) XXX_Size() int {
	return xxx_messageInfo_DeleteRoleResp.Size(m)
}
func (m *DeleteRoleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoleResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoleResp proto.InternalMessageInfo

func (m *DeleteRoleResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteRoleResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SelectRoleReq struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRoleReq) Reset()         { *m = SelectRoleReq{} }
func (m *SelectRoleReq) String() string { return proto.CompactTextString(m) }
func (*SelectRoleReq) ProtoMessage()    {}
func (*SelectRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{4}
}

func (m *SelectRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRoleReq.Unmarshal(m, b)
}
func (m *SelectRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRoleReq.Marshal(b, m, deterministic)
}
func (m *SelectRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRoleReq.Merge(m, src)
}
func (m *SelectRoleReq) XXX_Size() int {
	return xxx_messageInfo_SelectRoleReq.Size(m)
}
func (m *SelectRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRoleReq proto.InternalMessageInfo

func (m *SelectRoleReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *SelectRoleReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type AccessRoleReq struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	PrivilegeIds         []int32  `protobuf:"varint,2,rep,packed,name=privilegeIds,proto3" json:"privilegeIds,omitempty"`
	CreatedBy            string   `protobuf:"bytes,3,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessRoleReq) Reset()         { *m = AccessRoleReq{} }
func (m *AccessRoleReq) String() string { return proto.CompactTextString(m) }
func (*AccessRoleReq) ProtoMessage()    {}
func (*AccessRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{5}
}

func (m *AccessRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessRoleReq.Unmarshal(m, b)
}
func (m *AccessRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessRoleReq.Marshal(b, m, deterministic)
}
func (m *AccessRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessRoleReq.Merge(m, src)
}
func (m *AccessRoleReq) XXX_Size() int {
	return xxx_messageInfo_AccessRoleReq.Size(m)
}
func (m *AccessRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccessRoleReq proto.InternalMessageInfo

func (m *AccessRoleReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *AccessRoleReq) GetPrivilegeIds() []int32 {
	if m != nil {
		return m.PrivilegeIds
	}
	return nil
}

func (m *AccessRoleReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

type AccessRoleResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessRoleResp) Reset()         { *m = AccessRoleResp{} }
func (m *AccessRoleResp) String() string { return proto.CompactTextString(m) }
func (*AccessRoleResp) ProtoMessage()    {}
func (*AccessRoleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{6}
}

func (m *AccessRoleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessRoleResp.Unmarshal(m, b)
}
func (m *AccessRoleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessRoleResp.Marshal(b, m, deterministic)
}
func (m *AccessRoleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessRoleResp.Merge(m, src)
}
func (m *AccessRoleResp) XXX_Size() int {
	return xxx_messageInfo_AccessRoleResp.Size(m)
}
func (m *AccessRoleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessRoleResp.DiscardUnknown(m)
}

var xxx_messageInfo_AccessRoleResp proto.InternalMessageInfo

func (m *AccessRoleResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AccessRoleResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Role struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	RoleDesc             string   `protobuf:"bytes,3,opt,name=roleDesc,proto3" json:"roleDesc,omitempty"`
	CreatedOn            int32    `protobuf:"varint,4,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int32    `protobuf:"varint,6,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,7,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int32    `protobuf:"varint,8,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{7}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Role) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *Role) GetRoleDesc() string {
	if m != nil {
		return m.RoleDesc
	}
	return ""
}

func (m *Role) GetCreatedOn() int32 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Role) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Role) GetUpdatedOn() int32 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Role) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Role) GetDeletedOn() int32 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

type RoleResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role                 *Role    `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleResp) Reset()         { *m = RoleResp{} }
func (m *RoleResp) String() string { return proto.CompactTextString(m) }
func (*RoleResp) ProtoMessage()    {}
func (*RoleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{8}
}

func (m *RoleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleResp.Unmarshal(m, b)
}
func (m *RoleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleResp.Marshal(b, m, deterministic)
}
func (m *RoleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleResp.Merge(m, src)
}
func (m *RoleResp) XXX_Size() int {
	return xxx_messageInfo_RoleResp.Size(m)
}
func (m *RoleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoleResp proto.InternalMessageInfo

func (m *RoleResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RoleResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RoleResp) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type SelectRolesResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role                 []*Role  `protobuf:"bytes,3,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRolesResp) Reset()         { *m = SelectRolesResp{} }
func (m *SelectRolesResp) String() string { return proto.CompactTextString(m) }
func (*SelectRolesResp) ProtoMessage()    {}
func (*SelectRolesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{9}
}

func (m *SelectRolesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRolesResp.Unmarshal(m, b)
}
func (m *SelectRolesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRolesResp.Marshal(b, m, deterministic)
}
func (m *SelectRolesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRolesResp.Merge(m, src)
}
func (m *SelectRolesResp) XXX_Size() int {
	return xxx_messageInfo_SelectRolesResp.Size(m)
}
func (m *SelectRolesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRolesResp.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRolesResp proto.InternalMessageInfo

func (m *SelectRolesResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SelectRolesResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SelectRolesResp) GetRole() []*Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoleReq)(nil), "devops.integral.upm.srv.service.CreateRoleReq")
	proto.RegisterType((*UpdateRoleReq)(nil), "devops.integral.upm.srv.service.UpdateRoleReq")
	proto.RegisterType((*DeleteRoleReq)(nil), "devops.integral.upm.srv.service.DeleteRoleReq")
	proto.RegisterType((*DeleteRoleResp)(nil), "devops.integral.upm.srv.service.DeleteRoleResp")
	proto.RegisterType((*SelectRoleReq)(nil), "devops.integral.upm.srv.service.SelectRoleReq")
	proto.RegisterType((*AccessRoleReq)(nil), "devops.integral.upm.srv.service.AccessRoleReq")
	proto.RegisterType((*AccessRoleResp)(nil), "devops.integral.upm.srv.service.AccessRoleResp")
	proto.RegisterType((*Role)(nil), "devops.integral.upm.srv.service.Role")
	proto.RegisterType((*RoleResp)(nil), "devops.integral.upm.srv.service.RoleResp")
	proto.RegisterType((*SelectRolesResp)(nil), "devops.integral.upm.srv.service.SelectRolesResp")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8) }

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcf, 0x6e, 0x95, 0x40,
	0x14, 0xc6, 0xc3, 0xbf, 0x5b, 0x7a, 0x2a, 0x35, 0xce, 0xc2, 0x10, 0x62, 0x62, 0x33, 0x89, 0x49,
	0xdd, 0x8c, 0xa6, 0xae, 0x5c, 0xda, 0xe2, 0xa2, 0x1b, 0x9b, 0xd0, 0xf8, 0x00, 0x08, 0x27, 0x84,
	0x04, 0x2e, 0xc8, 0x00, 0xc9, 0x5d, 0x98, 0xf8, 0x50, 0x3e, 0x96, 0x0f, 0x61, 0x66, 0x28, 0x0c,
	0x73, 0x4d, 0x04, 0xac, 0x2e, 0xcf, 0x39, 0xf7, 0x9c, 0xdf, 0x7c, 0x9c, 0x99, 0xef, 0x02, 0x34,
	0x55, 0x81, 0xac, 0x6e, 0xaa, 0xb6, 0x22, 0x2f, 0x53, 0xec, 0xab, 0x9a, 0xb3, 0x7c, 0xdf, 0x62,
	0xd6, 0xc4, 0x05, 0xeb, 0xea, 0x92, 0xf1, 0xa6, 0x67, 0x1c, 0x9b, 0x3e, 0x4f, 0x90, 0x22, 0x78,
	0x37, 0x0d, 0xc6, 0x2d, 0x46, 0x55, 0x81, 0x11, 0x7e, 0x25, 0x01, 0xb8, 0xa2, 0xff, 0x53, 0x5c,
	0xa2, 0x6f, 0x5c, 0x18, 0x97, 0xa7, 0xd1, 0x14, 0x8f, 0xb5, 0x10, 0x79, 0xe2, 0x9b, 0xaa, 0x26,
	0x62, 0xf2, 0x02, 0x4e, 0x13, 0x39, 0x28, 0xbd, 0x3e, 0xf8, 0x96, 0x2c, 0xaa, 0x04, 0xfd, 0x06,
	0xde, 0xe7, 0x3a, 0x9d, 0x61, 0x9e, 0xc3, 0x4e, 0xb4, 0xde, 0xa6, 0x12, 0xe2, 0x44, 0x0f, 0x91,
	0x86, 0x37, 0xff, 0x80, 0xb7, 0x7e, 0xc7, 0x77, 0x12, 0x20, 0xf0, 0xf6, 0x80, 0x9f, 0x12, 0xf4,
	0x23, 0x78, 0x21, 0x16, 0xb8, 0x8c, 0xd7, 0xc6, 0x98, 0xc7, 0x63, 0x42, 0x38, 0x9f, 0x8f, 0xe1,
	0x35, 0xf1, 0xe1, 0x84, 0x77, 0x49, 0x82, 0x9c, 0xcb, 0x41, 0x6e, 0x34, 0x86, 0xa2, 0x52, 0x22,
	0xe7, 0x71, 0x36, 0xea, 0x18, 0x43, 0x7a, 0x03, 0xde, 0x3d, 0x16, 0x98, 0xb4, 0x8f, 0xf8, 0x16,
	0x34, 0x07, 0xef, 0x83, 0x04, 0x2d, 0x0d, 0xa1, 0xf0, 0xa4, 0x6e, 0xf2, 0x3e, 0x2f, 0x30, 0xc3,
	0xdb, 0x94, 0xfb, 0xe6, 0x85, 0x75, 0xe9, 0x44, 0x5a, 0x6e, 0x61, 0x77, 0x21, 0x9c, 0xcf, 0x51,
	0x7f, 0xa9, 0xfa, 0xa7, 0x01, 0xb6, 0x18, 0xf0, 0x3f, 0x36, 0xff, 0x70, 0xd6, 0xbb, 0xbd, 0xdc,
	0xbc, 0x13, 0xa9, 0x84, 0x2e, 0xcd, 0x39, 0x92, 0x36, 0x5b, 0xf7, 0xdd, 0xde, 0xdf, 0x0d, 0xbd,
	0x53, 0x42, 0xbf, 0x0c, 0x27, 0x47, 0x97, 0x41, 0x54, 0x53, 0x79, 0x19, 0x44, 0xaf, 0x3b, 0xf4,
	0x4e, 0x09, 0x7a, 0x00, 0xf7, 0x31, 0x9f, 0x8b, 0xbc, 0x07, 0x5b, 0x28, 0x94, 0x6a, 0xcf, 0xae,
	0x5e, 0xb1, 0x85, 0x77, 0xcc, 0x24, 0x4c, 0xb6, 0xd0, 0xef, 0x06, 0x3c, 0x55, 0x17, 0x8c, 0xff,
	0x83, 0x23, 0x58, 0x1b, 0x8f, 0x70, 0xf5, 0xc3, 0x86, 0x33, 0x11, 0xde, 0x0f, 0x25, 0x92, 0x01,
	0x28, 0x97, 0x21, 0x6c, 0x71, 0x94, 0x66, 0x49, 0xc1, 0xeb, 0x75, 0x68, 0xa1, 0x33, 0x03, 0x50,
	0x3e, 0xb3, 0x02, 0xa4, 0x99, 0xd2, 0x16, 0x50, 0x09, 0xa0, 0xac, 0x60, 0x05, 0x48, 0xb3, 0x9f,
	0xe0, 0xcd, 0xa6, 0xdf, 0xf3, 0x9a, 0x74, 0xf0, 0x6c, 0xb6, 0xd2, 0xeb, 0x83, 0x7c, 0x15, 0xcb,
	0x54, 0xcd, 0x67, 0x82, 0xb7, 0x1b, 0x7e, 0xcf, 0x47, 0x95, 0xea, 0xe9, 0xaf, 0xe0, 0x69, 0x96,
	0xb4, 0x42, 0xa5, 0xee, 0x2b, 0x5f, 0x76, 0xf2, 0x4f, 0xeb, 0xdd, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf5, 0x50, 0x6c, 0xb7, 0xc2, 0x06, 0x00, 0x00,
}
