// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project.proto

package devops_integral_upm_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProjectReq struct {
	ProjectCode          string   `protobuf:"bytes,1,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
	ProjectDesc          string   `protobuf:"bytes,3,opt,name=projectDesc,proto3" json:"projectDesc,omitempty"`
	ProjectOwner         int32    `protobuf:"varint,4,opt,name=projectOwner,proto3" json:"projectOwner,omitempty"`
	CreatedBy            string   `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectReq) Reset()         { *m = CreateProjectReq{} }
func (m *CreateProjectReq) String() string { return proto.CompactTextString(m) }
func (*CreateProjectReq) ProtoMessage()    {}
func (*CreateProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{0}
}

func (m *CreateProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectReq.Unmarshal(m, b)
}
func (m *CreateProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectReq.Marshal(b, m, deterministic)
}
func (m *CreateProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectReq.Merge(m, src)
}
func (m *CreateProjectReq) XXX_Size() int {
	return xxx_messageInfo_CreateProjectReq.Size(m)
}
func (m *CreateProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectReq proto.InternalMessageInfo

func (m *CreateProjectReq) GetProjectCode() string {
	if m != nil {
		return m.ProjectCode
	}
	return ""
}

func (m *CreateProjectReq) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *CreateProjectReq) GetProjectDesc() string {
	if m != nil {
		return m.ProjectDesc
	}
	return ""
}

func (m *CreateProjectReq) GetProjectOwner() int32 {
	if m != nil {
		return m.ProjectOwner
	}
	return 0
}

func (m *CreateProjectReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

type UpdateProjectReq struct {
	ProjectId            int32    `protobuf:"varint,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	ProjectCode          string   `protobuf:"bytes,2,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	ProjectName          string   `protobuf:"bytes,3,opt,name=projectName,proto3" json:"projectName,omitempty"`
	ProjectDesc          string   `protobuf:"bytes,4,opt,name=projectDesc,proto3" json:"projectDesc,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectReq) Reset()         { *m = UpdateProjectReq{} }
func (m *UpdateProjectReq) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectReq) ProtoMessage()    {}
func (*UpdateProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{1}
}

func (m *UpdateProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectReq.Unmarshal(m, b)
}
func (m *UpdateProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectReq.Marshal(b, m, deterministic)
}
func (m *UpdateProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectReq.Merge(m, src)
}
func (m *UpdateProjectReq) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectReq.Size(m)
}
func (m *UpdateProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectReq proto.InternalMessageInfo

func (m *UpdateProjectReq) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *UpdateProjectReq) GetProjectCode() string {
	if m != nil {
		return m.ProjectCode
	}
	return ""
}

func (m *UpdateProjectReq) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *UpdateProjectReq) GetProjectDesc() string {
	if m != nil {
		return m.ProjectDesc
	}
	return ""
}

func (m *UpdateProjectReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

type ProjectResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Project              *Project `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectResp) Reset()         { *m = ProjectResp{} }
func (m *ProjectResp) String() string { return proto.CompactTextString(m) }
func (*ProjectResp) ProtoMessage()    {}
func (*ProjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{2}
}

func (m *ProjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectResp.Unmarshal(m, b)
}
func (m *ProjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectResp.Marshal(b, m, deterministic)
}
func (m *ProjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectResp.Merge(m, src)
}
func (m *ProjectResp) XXX_Size() int {
	return xxx_messageInfo_ProjectResp.Size(m)
}
func (m *ProjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectResp proto.InternalMessageInfo

func (m *ProjectResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ProjectResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProjectResp) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Project struct {
	ProjectId            int32    `protobuf:"varint,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	ProjectCode          string   `protobuf:"bytes,2,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	ProjectName          string   `protobuf:"bytes,3,opt,name=projectName,proto3" json:"projectName,omitempty"`
	ProjectDesc          string   `protobuf:"bytes,4,opt,name=projectDesc,proto3" json:"projectDesc,omitempty"`
	ProjectOwner         int32    `protobuf:"varint,5,opt,name=projectOwner,proto3" json:"projectOwner,omitempty"`
	CreatedOn            int32    `protobuf:"varint,6,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,7,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int32    `protobuf:"varint,8,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,9,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int32    `protobuf:"varint,10,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{3}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetProjectId() int32 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Project) GetProjectCode() string {
	if m != nil {
		return m.ProjectCode
	}
	return ""
}

func (m *Project) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Project) GetProjectDesc() string {
	if m != nil {
		return m.ProjectDesc
	}
	return ""
}

func (m *Project) GetProjectOwner() int32 {
	if m != nil {
		return m.ProjectOwner
	}
	return 0
}

func (m *Project) GetCreatedOn() int32 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Project) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Project) GetUpdatedOn() int32 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Project) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Project) GetDeletedOn() int32 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

type SelectUserProjectsReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=projectName,proto3" json:"projectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserProjectsReq) Reset()         { *m = SelectUserProjectsReq{} }
func (m *SelectUserProjectsReq) String() string { return proto.CompactTextString(m) }
func (*SelectUserProjectsReq) ProtoMessage()    {}
func (*SelectUserProjectsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{4}
}

func (m *SelectUserProjectsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserProjectsReq.Unmarshal(m, b)
}
func (m *SelectUserProjectsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserProjectsReq.Marshal(b, m, deterministic)
}
func (m *SelectUserProjectsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserProjectsReq.Merge(m, src)
}
func (m *SelectUserProjectsReq) XXX_Size() int {
	return xxx_messageInfo_SelectUserProjectsReq.Size(m)
}
func (m *SelectUserProjectsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserProjectsReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserProjectsReq proto.InternalMessageInfo

func (m *SelectUserProjectsReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SelectUserProjectsReq) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type UserProjectsResp struct {
	Success              bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Projects             []*Project `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserProjectsResp) Reset()         { *m = UserProjectsResp{} }
func (m *UserProjectsResp) String() string { return proto.CompactTextString(m) }
func (*UserProjectsResp) ProtoMessage()    {}
func (*UserProjectsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{5}
}

func (m *UserProjectsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProjectsResp.Unmarshal(m, b)
}
func (m *UserProjectsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProjectsResp.Marshal(b, m, deterministic)
}
func (m *UserProjectsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProjectsResp.Merge(m, src)
}
func (m *UserProjectsResp) XXX_Size() int {
	return xxx_messageInfo_UserProjectsResp.Size(m)
}
func (m *UserProjectsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProjectsResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserProjectsResp proto.InternalMessageInfo

func (m *UserProjectsResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserProjectsResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserProjectsResp) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProjectReq)(nil), "devops.integral.upm.srv.service.CreateProjectReq")
	proto.RegisterType((*UpdateProjectReq)(nil), "devops.integral.upm.srv.service.UpdateProjectReq")
	proto.RegisterType((*ProjectResp)(nil), "devops.integral.upm.srv.service.ProjectResp")
	proto.RegisterType((*Project)(nil), "devops.integral.upm.srv.service.Project")
	proto.RegisterType((*SelectUserProjectsReq)(nil), "devops.integral.upm.srv.service.SelectUserProjectsReq")
	proto.RegisterType((*UserProjectsResp)(nil), "devops.integral.upm.srv.service.UserProjectsResp")
}

func init() { proto.RegisterFile("project.proto", fileDescriptor_8340e6318dfdfac2) }

var fileDescriptor_8340e6318dfdfac2 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0xae, 0x9a, 0x50,
	0x10, 0x0d, 0x20, 0x22, 0x63, 0x6d, 0xcc, 0x4d, 0xda, 0xdc, 0x18, 0x93, 0x12, 0x56, 0x2e, 0x1a,
	0x92, 0xda, 0xa4, 0x1f, 0xa0, 0x6e, 0xba, 0xa9, 0x2d, 0xc6, 0x0f, 0xa0, 0x30, 0x31, 0x36, 0x0a,
	0xb7, 0xf7, 0x82, 0x4d, 0x57, 0x5d, 0x75, 0xd7, 0xcf, 0xe9, 0xaa, 0x3f, 0xd0, 0x2f, 0x7a, 0xfb,
	0x17, 0xe0, 0x82, 0x5c, 0x7c, 0x79, 0xe8, 0x5b, 0xbd, 0xe5, 0x1c, 0x66, 0xce, 0x9c, 0xb9, 0x73,
	0x18, 0x18, 0x31, 0x9e, 0x7c, 0xc3, 0x30, 0xf5, 0x18, 0x4f, 0xd2, 0x84, 0xbc, 0x89, 0xf0, 0x94,
	0x30, 0xe1, 0xed, 0xe3, 0x14, 0x77, 0x3c, 0x38, 0x78, 0x19, 0x3b, 0x7a, 0x82, 0x9f, 0x3c, 0x81,
	0xfc, 0xb4, 0x0f, 0xd1, 0xfd, 0xa7, 0xc1, 0x78, 0xc9, 0x31, 0x48, 0xf1, 0x73, 0x59, 0xe8, 0xe3,
	0x77, 0xe2, 0xc0, 0x50, 0xd2, 0x2c, 0x93, 0x08, 0xa9, 0xe6, 0x68, 0x33, 0xdb, 0x6f, 0x42, 0x8d,
	0x8c, 0x4f, 0xc1, 0x11, 0xa9, 0xae, 0x64, 0xe4, 0x50, 0x23, 0x63, 0x85, 0x22, 0xa4, 0x86, 0x92,
	0x91, 0x43, 0xc4, 0x85, 0x17, 0x32, 0x5c, 0xff, 0x88, 0x91, 0xd3, 0x9e, 0xa3, 0xcd, 0x4c, 0x5f,
	0xc1, 0xc8, 0x14, 0xec, 0xb0, 0x50, 0x17, 0x2d, 0x7e, 0x52, 0xb3, 0xe0, 0x38, 0x03, 0xee, 0x5f,
	0x0d, 0xc6, 0x5b, 0x16, 0xa9, 0xe2, 0xa7, 0x60, 0x4b, 0x8a, 0x8f, 0x51, 0x21, 0xdd, 0xf4, 0xcf,
	0x40, 0x7b, 0x34, 0xbd, 0x73, 0x34, 0xa3, 0x73, 0xb4, 0xde, 0xe5, 0x68, 0x53, 0xb0, 0xb3, 0x42,
	0x57, 0x43, 0x76, 0x0d, 0xb8, 0xbf, 0x35, 0x18, 0xd6, 0x82, 0x05, 0x23, 0x14, 0x2c, 0x91, 0x85,
	0x21, 0x0a, 0x51, 0xe8, 0x1d, 0xf8, 0x55, 0x98, 0x7f, 0x39, 0xa2, 0x10, 0xc1, 0xae, 0x52, 0x5a,
	0x85, 0x64, 0x01, 0x96, 0x6c, 0x58, 0x28, 0x1c, 0xce, 0x67, 0x5e, 0xc7, 0xaa, 0xbd, 0xaa, 0x65,
	0x55, 0xe8, 0xfe, 0xd7, 0xc1, 0x92, 0xe0, 0xb3, 0x78, 0xb5, 0xb6, 0x21, 0xcc, 0x47, 0x0d, 0xb1,
	0x8e, 0x69, 0xbf, 0xd4, 0x59, 0x03, 0xaa, 0x5d, 0xac, 0x96, 0x5d, 0x1a, 0x5b, 0x59, 0xc7, 0x74,
	0x50, 0xd6, 0xd6, 0x80, 0xba, 0x33, 0xbb, 0xb5, 0xb3, 0xfc, 0x6b, 0x84, 0x07, 0x2c, 0x6b, 0xa1,
	0xac, 0xad, 0x01, 0xf7, 0x0b, 0xbc, 0xda, 0xe0, 0x01, 0xc3, 0x74, 0x2b, 0x90, 0xcb, 0x27, 0x15,
	0xb9, 0x19, 0x5f, 0x43, 0x3f, 0x13, 0xc8, 0xeb, 0x37, 0x95, 0x51, 0xf7, 0xff, 0xe3, 0xfe, 0xc9,
	0xbd, 0xad, 0xb0, 0x3d, 0xd1, 0x29, 0x2b, 0x18, 0x48, 0x5e, 0x41, 0x0d, 0xc7, 0xb8, 0xc9, 0x2a,
	0x75, 0xe5, 0xfc, 0x4e, 0x87, 0x97, 0x12, 0xdd, 0x94, 0x49, 0x84, 0xc1, 0x48, 0xb9, 0x1c, 0xe4,
	0x5d, 0x27, 0x6f, 0xfb, 0xd2, 0x4c, 0xde, 0x5e, 0x2d, 0x25, 0x1f, 0x9f, 0xc1, 0x48, 0xf9, 0xdd,
	0xaf, 0xe8, 0xd8, 0x3e, 0x0f, 0x37, 0x76, 0xfc, 0x05, 0xe4, 0x72, 0xb1, 0xe4, 0x43, 0x27, 0xc7,
	0x83, 0x6e, 0x98, 0x5c, 0x21, 0xb7, 0xb5, 0xf1, 0xaf, 0xfd, 0xe2, 0x8e, 0xbf, 0xbf, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xa2, 0xa9, 0x05, 0xf2, 0xd8, 0x05, 0x00, 0x00,
}
